### PR TITLE
Marek's code migration 

### PR DESCRIPTION
**Pull request by rNLKJA**
### Description:

This PR represents a significant milestone in the Genomics Metadata Multiplexing (GMM) project, transitioning the web application from Flask (Python) to Shiny/R. This migration aims to leverage the computational and interactive capabilities of Shiny within the R ecosystem, facilitating deployment on the WEHI Milton server and enhancing the app's usability and functionality.

#### Main Functionalities:

- **Plate Layout to Spreadsheet Conversion**: Enables users to generate sample (primer index) spreadsheets from color-coded plate designs.
- **Collate FCS Data**: Allows for the aggregation of data from multiple FCS files into a single CSV file.
- **Merge FCS Data**: Facilitates the integration of FACS data into a row-wise sample spreadsheet, correlating plate, sample ID, and well position.

#### Implementation Highlights:

- **UI Redesign**: The application now features a tabbed interface, with separate tabs dedicated to each main functionality, improving navigability and user experience.
- **File Upload Mechanism**: Before any operation, users are prompted to upload the required files (e.g., Plate spreadsheet, FCS file, Sample sheet, Template sheet) through designated file selection fields.
- **Dynamic Preview Table**: After initiating a conversion operation, users are presented with a preview table of the results, allowing for verification before finalizing the output.
- **Downloadable Results**: Once users confirm the accuracy of the preview table, they have the option to download the resulting file, facilitating seamless integration into their workflows.

#### Motivation for Migration:

The decision to migrate from Flask to Shiny/R was driven by several factors:

- **Integration with R Ecosystem**: Many of the analytical and data processing tasks inherent to the GMM project are more naturally suited to the R ecosystem.
- **Interactive Capabilities of Shiny**: Shiny's robust framework for building interactive web applications significantly enhances the user experience.
- **Deployment Considerations**: Deploying on the WEHI Milton server is more straightforward with a Shiny/R application, aligning with project goals and resource optimization.

#### How to Test:

1. Navigate to the newly designed tabs for each main functionality.
2. Upload the required files using the file selection fields.
3. Initiate conversion operations and review the dynamic preview table.
4. Confirm the results and download the final file.

#### Request for Feedback:

Feedback on the new Shiny/R implementation, especially regarding usability, performance, and any encountered issues, is highly welcomed. Please provide your insights and suggestions to further refine and enhance the application.

### CODE REVIEW

**Comment by rNLKJA** [comment]
Current progress: we have a wireframe 

https://github.com/WEHI-ResearchComputing/Genomics-Metadata-Multiplexing/assets/62606765/6f1958fd-6a6b-4ff6-a636-f505d8c020ea

**Comment by rNLKJA** [comment]
Uploaded environment files, before you start the application, you must source the package dependencies via: `renv::restore()`.

In future, if we add more packages, please use `renv::shapshot()` to generate a new `renv.lock` file.

**Comment by rowlandm** [comment]
> Uploaded environment files, before you start the application, you must source the package dependencies via: `renv::restore()`.
> 
> In future, if we add more packages, please use `renv::shapshot()` to generate a new `renv.lock` file.

May need to document this in the README or in the wiki

**Comment by rNLKJA** [comment]
> > Uploaded environment files, before you start the application, you must source the package dependencies via: `renv::restore()`.
> > In future, if we add more packages, please use `renv::shapshot()` to generate a new `renv.lock` file.
> 
> May need to document this in the README or in the wiki

just ask GPT generating a wiki :D
here is the [wiki link](https://github.com/WEHI-ResearchComputing/Genomics-Metadata-Multiplexing/wiki/Step%E2%80%90by%E2%80%90Step-Guide-to-Creating-an-R-Development-Environment-Step-1:-Install-R-and-RStudio)

**Comment by rowlandm** [comment]
> > > Uploaded environment files, before you start the application, you must source the package dependencies via: `renv::restore()`.
> > > In future, if we add more packages, please use `renv::shapshot()` to generate a new `renv.lock` file.
> > 
> > 
> > May need to document this in the README or in the wiki
> 
> just ask GPT generating a wiki :D here is the [wiki link](https://github.com/WEHI-ResearchComputing/Genomics-Metadata-Multiplexing/wiki/Step%E2%80%90by%E2%80%90Step-Guide-to-Creating-an-R-Development-Environment-Step-1:-Install-R-and-RStudio)

ChatGPT is fine to use, provided you check that it says is accurate. It tends to lie.

https://www.rollingstone.com/culture/culture-features/chatgpt-defamation-lawsuit-openai-1234766693/

https://edition.cnn.com/2023/08/29/tech/ai-chatbot-hallucinations/index.html

**Comment by rNLKJA** [comment]
image
image
image

Updates:
- Integrate all functions into a single tab. There are two tabs available for the user, one for the homepage and another one for FCS File Operations
- Removed tutorial page, we see for each FCS operation selection panel, we have a lot of space to work around, we probably want to embed a tutorial with each function

TODO:
- [ ] implement the file upload function, it should upload a list of files,
  - [ ] and we need a placeholder to tell users which file they want to upload
- [ ] main panel display
- [ ] we can start migrating `operations.py` from Marek's code

**Pull request merged**
